# To inform the algorithm to exit automatically when no data is received
autoexit:           1

# Declare the lidar topics to merge
lidar_topic:        [
                      "/os_cloud_node/points"
                    ]

merged_lidar_topic: "/merged_pc"

# Lidar extrinsics: Transform of coordinates in lidar's frame to body
# NOTE TO USER: The (4,4) entry of the extrinsics is used to declare
# whether stamp is at beginning (1.000) or end (0.000) of scan
lidar_extr:         [
                      # Hesai
                      0.006609639848469365, -0.9999773650294649,     0.0012578115132016717, -0.006730146149038548,
                     -0.9999762249571927,   -0.006612093869054189,  -0.0019569708811106104, -0.006897049862999071,
                      0.001965243352927244, -0.0012448467359610184, -0.9999972940839232,     0.049898628062256645,
                      0.0,                   0.0,                    0.0,                    1.0
                    ]

# Minimum lidar range to admit
min_range:          0.5

# IMU topic
imu_topic:          "/alphasense/imu"

# Gravity constant
GRAV:               9.82

# IMU noises
# GYR_N:              0.0010679343003532472
# GYR_W:              2.6541629581345176e-05
# ACC_N:              0.0001688956233495657
# ACC_W:              9.782812831313576e-07

GYR_N:              5.0e-3
GYR_W:              3.0e-6
ACC_N:              6.0e-2
ACC_W:              8.0e-6

# Weightage of a basic lidar factor
lidar_weight:       1.0

# Number of packets to process at time
WINDOW_SIZE:        4
# Number of substates to give to each packet
N_SUB_SEG:          4

# Downsampling grid size, chose -1 for no downsampling
leaf_size:          0.05          # Downsample scale of input pointcloud, also the scale of ufomap leaf
assoc_spacing:      0.4
surfel_map_depth:   16
surfel_min_point:   8
surfel_min_depth:   1
surfel_query_depth: 7             # Equal to Dmax + 1. Dmax is defined in the paper
surfel_intsect_rad: 0.2           # r in the the paper
surfel_min_plnrty:  0.7

# Distance to surfel and min score thresholds
dis_to_surfel_max:  0.5
score_min:          0.05

# Downsample coefficient of lidar scans, ds_rate = n means keep every n-th point.
ds_rate:            [
                      2
                    ]

# Threshold to add new keyframe
kf_min_dis:         2.0
kf_min_angle:       10

# Optimization parameters
lidar_loss_thres:   10.0

# Solver:
# Trust region strategy: "lm", "dogleg"
trustRegType:       "lm"
# Linear Algebra library used: "eigen", "lapack", "cuda"
linAlgbLib:         "cuda" 
max_solve_time:     0.3
max_iterations:     30

# Sensors fused
fuse_lidar:         1
fuse_imu:           1

regularize_imu:     1
imu_init_time:      1.0
max_outer_iters:    3
max_lidar_factor:   4000   # Maximum number of lidar factors

# Loop closure parameters
loop_en:            1
loop_kf_nbr:        20    # Number of neighbour to check for loop closure
loop_kfid_mindiff:  20    # Only check for loop when keyframes have this much difference

icpMaxIter:         100   # Maximum iterations for ICP
icpFitnessThres:    0.6   # Fitness threshold for ICP check
histDis:            15    # Maximum correspondence distance for icp

# Bundle adjustment params
rib_edge:           100
odom_q_noise:       0.1
odom_p_noise:       0.1
loop_weight:        0.05

# Number of optimizations before quitting
debug_exit:        -1
publish_map:        0

# Log directory
log_dir:            "/home/tmn/slict_log/atv"