
# M2DGR
lidar_topic: /kitti/velo/pointcloud
imu_topic:  /kitti/oxts/imu


lidar_type: velodyne   # livox velodyne ouster
min_radius: 4.0
max_radius: 150.0
point_filter_num: 3
time_scale: 1000.0 # nclt: 0.001 other: 1000.0
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.5
voxel_map_resolution: 0.5
max_iterations: 10

acc_cov: 0.01
gyr_cov: 0.0001
ba_cov: 0.000001
bg_cov: 0.000001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001

# KITTI
t_imu_lidar : [8.086759e-01, -3.195559e-01, 7.997231e-01]
R_imu_lidar: [ 9.999976e-01, -7.854027e-04,  2.024406e-03,
              7.553071e-04,  9.998898e-01,  1.482454e-02, 
              -2.035826e-03, -1.482298e-02, 9.998881e-01]